In [48]:
import pandas as pd
import matplotlib.pyplot as plt
import glob
pd.set_option('display.max_columns', None)

files = glob.glob("teamstats/*.csv")
team_stats_for_each_year = [];
for file in files:
    df = pd.read_csv(file)
    df = df[['season', 'team' ,'completions', 'attempts', 'receiving_yards', 'receiving_tds', 'rushing_yards', 'rushing_tds', 'carries', 'sacks_suffered', 'rushing_fumbles_lost', 'sack_fumbles_lost', 'receiving_fumbles_lost', 'receiving_yards_after_catch', 'passing_interceptions', 'special_teams_tds', 'def_tackles_for_loss', 'def_fumbles_forced', 'def_sacks', 'def_qb_hits', 'def_interceptions', 'def_tds', 'penalties', 'penalty_yards', 'punt_return_yards', 'kickoff_return_yards', 'fg_made', 'fg_att']] 
    df.insert(2, 'passing_completion_per', df['completions'] / df['attempts'])
    df.insert(8, 'off_total_tds', df['receiving_tds'] + df['rushing_tds'])
    df.insert(8, 'off_total_yds', df['receiving_yards'] + df['rushing_yards'])
    df.insert(17, 'off_total_turnovers', df['rushing_fumbles_lost'] + df['sack_fumbles_lost'] + df['receiving_fumbles_lost'] + df['passing_interceptions'])
    df.insert(25,'def_turnovers_forced', df['def_fumbles_forced'] + df['def_interceptions'])
    df['special_teams_return_yards'] = df['kickoff_return_yards'] + df['punt_return_yards']
    col = df.pop('special_teams_tds')
    df.insert(28, 'special_teams_tds', col)
    df['fg_per'] = df['fg_made'] / df['fg_att']
    droppedColumns= ['completions', 'attempts', 'receiving_tds', 'rushing_tds', 'rushing_fumbles_lost', 'receiving_fumbles_lost', 'sack_fumbles_lost', 'passing_interceptions', 'def_fumbles_forced', 'def_interceptions', 'punt_return_yards', 'kickoff_return_yards', 'fg_made', 'fg_att']
    df = df.drop(columns=droppedColumns)
    team_stats_years.append(df)
    display(df.head(5))

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2009,ARI,0.660504,4205,1489,5694,43,364,26,1770,34,0,41,76,31,1,108,886,2,1592,0.947368
1,2009,ATL,0.582456,3697,1876,5573,41,451,27,1520,23,0,28,58,35,1,78,664,0,1596,0.655172
2,2009,BAL,0.629412,3637,2206,5843,43,467,37,1665,20,0,32,60,37,2,115,1094,1,1837,0.700000
3,2009,BUF,0.580499,2789,1867,4656,23,425,46,1351,25,0,34,70,42,2,107,855,0,1735,0.848485
4,2009,CAR,0.567742,3070,2498,5568,34,525,33,1240,29,0,31,67,44,1,88,698,0,1274,0.814815

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2021,ARI,0.702200,4619,2076,6695,50,496,39,2267,14,64,40,101,34,1,114,990,0,849,0.810811
1,2021,ATL,0.657941,3987,1451,5438,31,393,40,1732,26,44,17,59,26,2,92,753,0,1188,0.931034
2,2021,BAL,0.648118,4267,2479,6746,39,517,57,1717,25,60,33,96,17,1,102,852,0,1097,0.945946
3,2021,BUF,0.633588,4450,2209,6659,56,461,27,1752,21,71,41,91,31,1,113,980,0,1106,0.875000
4,2021,CAR,0.580968,3573,1842,5415,31,455,52,1831,29,69,39,94,23,0,107,864,1,833,0.896552

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2020,ARI,0.673043,4102,2237,6339,49,479,29,1855,21,80,48,100,26,0,113,868,0,661,0.766667
1,2020,ATL,0.649682,4620,1532,6152,40,409,41,1644,18,53,29,92,29,1,83,736,0,561,0.950000
2,2020,BAL,0.633005,2919,3071,5990,51,555,32,1262,18,62,39,116,35,0,104,961,1,857,0.896552
3,2020,BUF,0.687919,4786,1723,6509,56,411,27,1946,20,58,38,92,30,2,102,941,1,1365,0.823529
4,2020,CAR,0.678182,4129,1704,5833,35,407,36,2035,21,51,29,89,21,0,95,752,0,851,0.805556

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2008,ARI,0.664025,4874,1179,6053,45,339,28,2219,28,0,31,70,33,2,107,781,3,1867,0.892857
1,2008,ATL,0.610599,3440,2443,5883,39,560,17,1325,18,0,33,58,20,2,72,591,1,1787,0.935484
2,2008,BAL,0.602771,3085,2382,5467,36,591,34,1401,21,0,33,86,38,5,104,791,0,1385,0.800000
3,2008,BUF,0.645094,3302,1842,5144,30,439,38,1366,29,0,23,52,24,3,71,538,2,2280,0.789474
4,2008,CAR,0.594203,3284,2439,5723,45,504,20,1226,19,0,37,50,29,0,94,637,0,1825,0.903226

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2022,ARI,0.652108,3966,1873,5839,32,434,46,2058,24,71,36,106,23,3,118,916,0,975,0.875000
1,2022,ATL,0.619277,2927,2718,5645,34,559,37,1240,19,48,21,69,18,1,68,594,2,926,0.864865
2,2022,BAL,0.614754,3202,2720,5922,33,526,38,1370,21,68,48,95,28,0,82,678,1,873,0.860465
3,2022,BUF,0.628920,4291,2232,6523,50,430,33,1593,26,80,40,98,28,1,92,709,2,1184,0.870968
4,2022,CAR,0.584245,3246,2210,5456,32,483,36,1734,18,74,35,91,19,2,104,862,0,963,0.942857

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2023,ARI,0.639640,3430,2365,5795,35,471,42,1669,17,64,33,59,17,0,101,859,0,668,0.848485
1,2023,ATL,0.616981,3775,2159,5934,31,522,40,1769,28,56,42,98,27,1,84,743,0,475,0.864865
2,2023,BAL,0.663968,3881,2661,6542,53,541,41,1827,19,77,58,117,34,1,102,955,1,736,0.864865
3,2023,BUF,0.664940,4306,2212,6518,51,512,24,1973,27,80,53,117,32,2,106,883,1,709,0.827586
4,2023,CAR,0.597270,3245,1769,5014,20,445,65,1439,20,55,27,74,13,2,103,845,1,959,0.833333

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2024,ARI,0.688766,3859,2451,6310,39,463,30,1972,20,87,41,76,26,0,92,806,1,911,0.894737
1,2024,ATL,0.651163,4283,2219,6502,39,495,32,1958,22,79,31,74,24,3,99,828,0,991,0.707317
2,2024,BAL,0.666667,4189,3189,7378,62,554,24,2086,11,82,53,122,24,2,132,1120,0,1024,0.733333
3,2024,BUF,0.632692,3938,2230,6168,62,491,14,2186,8,93,37,94,34,2,112,833,0,934,0.827586
4,2024,CAR,0.623400,3411,1878,5289,40,410,36,1431,22,65,32,64,17,0,118,947,0,1237,0.846154

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2018,ARI,0.571717,2884,1342,4226,24,355,52,1254,28,85,49,90,20,0,101,786,1,831,0.705882
1,2018,ATL,0.693679,4949,1573,6522,47,351,42,2145,17,54,37,77,23,1,101,899,0,836,0.961538
2,2018,BAL,0.600719,3708,2441,6149,37,547,32,1553,19,85,42,104,21,0,116,940,1,1111,0.897436
3,2018,BUF,0.542169,3052,1984,5036,28,468,41,1354,30,76,36,87,36,0,116,992,0,1014,0.814815
4,2018,CAR,0.671403,4071,2136,6207,45,416,32,2053,20,76,34,71,26,0,92,818,0,747,0.904762

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2019,ARI,0.640794,3797,1990,5787,38,396,50,1880,18,81,40,91,26,0,121,956,0,932,0.885714
1,2019,ATL,0.671053,5049,1361,6410,39,362,50,1899,23,63,28,69,29,1,119,956,1,834,0.800000
2,2019,BAL,0.656818,3350,3296,6646,58,596,28,1447,14,66,37,111,28,2,109,867,0,699,0.965517
3,2019,BUF,0.582846,3476,2054,5530,34,465,40,1503,19,84,44,92,30,0,117,927,1,1045,0.785714
4,2019,CAR,0.603476,4134,1819,5953,37,386,58,2032,32,72,53,108,22,0,87,754,0,848,0.781250

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2025,ARI,0.657935,4354,1583,5937,38,366,59,2111,19,70,30,71,23,0,115,842,0,2196,0.757576
1,2025,ATL,0.609174,3703,2138,5841,36,477,26,1871,16,95,57,97,28,1,108,819,0,1699,0.820513
2,2025,BAL,0.658768,3278,2662,5940,46,507,45,1361,22,66,30,101,25,1,99,746,0,2109,0.882353
3,2025,BUF,0.694949,3981,2714,6695,59,547,40,2098,18,84,36,92,26,1,101,848,1,2036,0.904762
4,2025,CAR,0.638835,3304,1977,5281,33,461,35,1630,21,65,30,58,24,2,95,762,0,1480,0.827586

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2014,ARI,0.563380,3990,1308,5298,27,397,28,1604,17,82,35,83,27,3,91,707,1,694,0.878788
1,2014,ATL,0.661392,4758,1498,6256,39,372,31,2099,23,55,22,63,29,1,97,840,1,1413,0.906250
2,2014,BAL,0.620939,3986,2019,6005,43,448,19,1751,17,74,49,118,27,1,111,870,2,1369,0.852941
3,2014,BUF,0.626943,3856,1482,5338,30,402,39,2077,21,88,54,99,33,0,124,1031,3,1124,0.894737
4,2014,CAR,0.600000,3828,2036,5864,33,473,42,1427,21,64,40,80,36,2,83,756,1,1044,0.828571

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2015,ARI,0.628114,4775,1917,6692,51,452,27,1782,22,86,35,107,41,4,94,758,1,1059,0.903226
1,2015,ATL,0.660225,4602,1606,6208,34,420,32,1856,28,46,19,75,27,1,100,969,0,922,0.806452
2,2015,BAL,0.630178,4449,1478,5927,29,383,24,2138,26,79,37,94,14,1,122,1153,2,1307,0.825000
3,2015,BUF,0.634409,3600,2432,6032,42,509,42,1290,16,45,21,75,26,2,143,1249,0,1004,0.851852
4,2015,CAR,0.598802,3873,2282,6155,54,526,33,1494,19,86,44,110,46,4,103,887,0,689,0.833333

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2017,ARI,0.566890,3979,1386,5365,27,409,52,1457,25,84,37,96,32,1,110,880,0,880,0.800000
1,2017,ATL,0.647170,4146,1847,5993,33,430,24,1861,17,73,39,81,20,0,102,918,0,1072,0.871795
2,2017,BAL,0.640212,3235,1856,5091,34,460,27,1506,17,90,41,100,38,3,91,749,2,1258,0.918919
3,2017,BUF,0.606316,3065,2017,5082,28,487,47,1303,16,70,26,71,34,1,98,872,0,853,0.878788
4,2017,CAR,0.584830,3319,2102,5421,37,490,35,1623,21,69,50,105,25,0,83,682,2,1078,0.966667

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2016,ARI,0.592879,4425,1732,6157,48,399,41,1747,28,103,46,103,35,2,104,889,0,774,0.750000
1,2016,ATL,0.696462,4960,1928,6888,58,421,37,2267,11,58,34,81,29,3,104,847,0,757,0.918919
2,2016,BAL,0.646539,4343,1463,5806,30,367,33,2090,20,70,31,80,32,0,125,1111,1,882,0.974359
3,2016,BUF,0.603376,3250,2630,5880,46,492,46,1190,12,59,39,79,23,1,112,960,0,1143,0.760000
4,2016,CAR,0.543517,3962,1814,5776,37,453,36,1471,26,73,47,93,35,1,98,850,0,1030,0.789474

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2012,ARI,0.554276,3383,1204,4587,21,352,58,1363,31,68,38,85,35,2,102,857,1,1371,0.892857
1,2012,ATL,0.686179,4719,1397,6116,44,378,28,2061,18,70,29,70,35,1,55,415,0,845,0.868421
2,2012,BAL,0.596429,3996,1901,5897,39,444,38,1624,15,80,37,87,23,2,121,1127,3,2040,0.909091
3,2012,BUF,0.604697,3430,2217,5647,36,442,30,1805,33,60,36,66,33,1,104,871,3,1581,0.875000
4,2012,CAR,0.579592,3927,2088,6015,40,462,36,1744,17,63,39,68,28,3,98,835,0,1143,0.761905

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2006,ARI,0.590074,3919,1338,5257,29,421,34,1582,27,0,38,63,36,1,117,937,1,1860,0.756757
1,2006,ATL,0.534772,2682,2939,5621,30,537,47,942,20,0,37,55,31,1,96,877,0,1830,0.718750
2,2006,BAL,0.625954,3535,1637,5172,32,476,17,1391,22,0,60,103,41,5,109,878,0,1397,0.933333
3,2006,BUF,0.622685,3050,1552,4602,28,420,47,1243,26,0,35,60,29,2,87,629,1,1925,0.920000
4,2006,CAR,0.602968,3486,1659,5145,26,423,32,1553,25,0,41,69,30,2,103,744,0,1429,0.888889

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2007,ARI,0.604061,4220,1450,5670,41,402,24,1588,35,0,36,62,31,6,137,1130,1,2077,0.700000
1,2007,ATL,0.604317,3573,1520,5093,25,385,46,1740,24,0,25,36,32,0,105,891,0,2009,0.764706
2,2007,BAL,0.612208,3308,1797,5105,24,446,39,1292,34,0,32,65,28,1,106,858,3,1863,0.843750
3,2007,BUF,0.591011,2842,1800,4642,20,448,26,1414,21,0,23,62,30,2,78,633,2,1924,0.888889
4,2007,CAR,0.564356,2934,1824,4758,26,451,33,1285,26,0,23,46,32,1,95,801,0,1415,0.857143

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2013,ARI,0.632404,4291,1540,5831,36,422,41,1756,31,87,47,115,31,4,97,744,0,738,0.833333
1,2013,ATL,0.675266,4541,1247,5788,37,321,44,2138,26,58,32,59,23,2,91,788,0,909,0.888889
2,2013,BAL,0.586430,3914,1328,5242,26,423,48,1751,27,75,40,84,30,1,112,942,2,1772,0.926829
3,2013,BUF,0.572797,3373,2307,5680,31,546,48,1508,26,85,57,99,35,2,110,952,0,712,0.916667
4,2013,CAR,0.617336,3379,2026,5405,38,483,43,1613,16,90,59,105,31,4,80,671,0,928,0.888889

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2005,ARI,0.625373,4719,1138,5857,23,360,45,0,35,0,37,0,34,3,145,1185,0,2104,0.955556
1,2005,ATL,0.547672,2907,2559,5466,36,530,40,0,25,0,37,0,30,0,114,1043,1,1743,0.888889
2,2005,BAL,0.596085,3381,1611,4992,22,451,43,0,35,0,41,0,31,1,139,1067,0,1720,0.857143
3,2005,BUF,0.586957,2852,1605,4457,24,429,42,0,25,0,38,0,33,1,120,897,1,2271,0.828571
4,2005,CAR,0.599109,3485,1679,5164,42,487,27,0,24,0,42,0,40,2,91,732,0,1527,0.764706

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2011,ARI,0.558182,3954,1625,5579,33,389,54,1730,31,0,42,83,22,0,106,1004,4,1942,0.791667
1,2011,ATL,0.614478,4365,1834,6199,43,453,26,1786,20,0,32,82,32,2,93,769,0,878,0.931034
2,2011,BAL,0.577206,3629,1996,5625,36,459,33,1591,22,0,48,90,36,1,92,742,1,1392,0.769231
3,2011,BUF,0.615917,3857,1921,5778,36,391,23,1876,30,0,28,56,35,4,86,743,1,1182,0.741935
4,2011,CAR,0.601156,4089,2408,6497,47,445,35,1954,23,0,31,50,26,0,113,1013,1,1102,0.785714

,season,team,passing_completion_per,receiving_yards,rushing_yards,off_total_yds,off_total_tds,carries,sacks_suffered,receiving_yards_after_catch,off_total_turnovers,def_tackles_for_loss,def_sacks,def_qb_hits,def_turnovers_forced,def_tds,penalties,penalty_yards,special_teams_tds,special_teams_return_yards,fg_per
0,2010,ARI,0.508021,3264,1388,4652,19,320,50,1080,30,0,33,67,30,3,108,870,2,2378,0.888889
1,2010,ATL,0.625650,3725,1891,5616,42,497,23,1366,15,0,31,54,36,2,58,598,2,1451,0.903226
2,2010,BAL,0.627291,3629,1831,5460,36,487,40,1521,18,0,27,63,34,3,90,673,1,1676,0.896552
3,2010,BUF,0.570328,3363,1720,5083,30,401,34,1358,35,0,27,54,26,2,82,633,1,1794,0.761905
4,2010,CAR,0.528926,2635,1846,4481,16,428,50,1290,34,0,31,75,31,1,106,918,0,1992,0.862069